name: Run tests on each commit

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install && yarn test
